classifier_app/urls.py
from django.urls import path
from . import views

app_name = 'classifier_app'
urlpatterns = [
    path('', views.AnalyzerApi.as_view(), name='analyze'),
    path('file/', views.ShowFileOperations.as_view(), name='file_upload'),
    path('file/search/', views.SearchInFile.as_view(), name='file_search'),
    path('file/sentiment/', views.SentimentOfFile.as_view(), name='file_sentiment'),

]

sentiment_analyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifier_app.urls'))
]

classifier_app/models.py
from django.db import models

# Create your models here.

classifier_app/views.py
""" This module contains Apis to handle Sentiment Analysis on pdf """

import os
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render
from classifier.sentiment_analyzer import MessageClassifier
from django.views import View
import fitz
import re


class AnalyzerApi(View):
    """ Statement classifier Api """

    def post(self, request, *args, **kwargs):
        """
        Get Text from user and return its sentiment

        Returns:
            Html Page
        """

        text = str(self.request.POST.get('text'))
        classifier = MessageClassifier(text)
        data = {
            'data': classifier.analyze(),
        }
        return render(
            request=self.request,
            template_name='classifier_app/result_page.html',
            context=data
        )

    def get(self, request, *args, **kwargs):
        """
        Show Page so that user can input Text.
        """

        return render(
            request=self.request,
            template_name='classifier_app/page.html'
        )


class SentimentOfFile(View):
    """ Get file from user for processing"""

    def get(self, request, *args, **kwargs):
        """
        Show Page so that user can input Text.
        """

        return render(
            request=self.request,
            template_name='classifier_app/get_file.html'
        )

    def post(self, request, *args, **kwargs):
        """
        Get pdf from user and return its sentiment

        Returns:
            Html Page
        """

        file = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

        with fitz.open(filename) as doc:
            text = ""
            for page in doc:
                text += page.getText()
            # os.remove(filename)
            classifier = MessageClassifier(text)
            data = {
                'data': classifier.analyze()
            }
            return render(
                request=self.request,
                template_name='classifier_app/result_page.html',
                context=data
            )


class ShowFileOperations(View):
    """ Show operations available on file """

    def get(self, request, *args, **kwargs):
        """ return Page containing operations file """
        return render(
            request=request,
            template_name='classifier_app/file_upload.html',
            context={}
        )


class SearchInFile(View):
    """ Search in file """
    def get(self, request, *args, **kwargs):
        """ get the file and search keyword from user """
        return render(
            request=request,
            template_name='classifier_app/search_in_file.html',
            context={}
        )

    def post(self, request, *args, **kwargs):
        """ show the search results to user """
        file = request.FILES['myfile']
        query = str(self.request.POST.get('query'))
        fs = FileSystemStorage()
        filename = fs.save(file.name, file)

        with fitz.open(filename) as doc:
            text = ""
            page_locations = []
            for page in doc:
                t = page.get_text()
                text += t
                if query in t:
                    page_locations.append(page.number + 1)

            result = text.lower().replace(query, '<b style="color:#008000">{}</b>'.format(query))
            data = {
                'data': text,
                'query': result,
                'page_locations': page_locations,
            }

        return render(
            request=request,
            template_name='classifier_app/search_result_file.html',
            context=data
        )

classifier_app/templates/classifier_app/file_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Upload File</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <hr>
        <a href="{url 'classifier_app':file_upload}">
            <button type="submit" class="btn btn-primary">Upload</button>
        </a>
  </form>

</body>
</html>

classifier_app/templates/classifier_app/get_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>File Sentiments</title>
</head>
<body>

    <div class="container">
        <h1 style="color:gray">Select File</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="myfile">
            <hr>

            <br>
            <a href="{% url 'classifier_app:file_search'%}">
                <button type="submit" class="btn btn-primary">
                    Check Sentiment
                </button>
            </a>
      </form>
    </div>

</body>
</html>

classifier_app/templates/classifier_app/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Analyzer</title>
    	    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
        <style>
textarea {
  width: 50%;
  height: 150px;
  padding: 12px 20px;
  box-sizing: border-box;
  border: 2px solid #ccc;
  border-radius: 4px;
  background-color: #f8f8f8;
  font-size: 16px;
  resize: none;
}
</style>
</head>
<body>
    <div class="container">
        <h1 style="color:SlateBlue">Sentiment Analyzer</h1>
        <hr>
        <br>
        <form method="post">
            {% csrf_token %}
            <b>Enter Text: </b>
            <br>
        <textarea cols="30" rows="5" name="text"></textarea>
        <br>
        <br>
        <a href="{% url 'classifier_app:analyze'%}">
            <button type="submit" class="btn btn-primary">
                Check Sentiment
            </button>
        </a>
            <hr>
            <h3>OR</h3>
            <hr>
        </form>
        <a href="{% url 'classifier_app:file_upload'%}">
            <button type="submit" class="btn btn-primary">
                Analyze File
            </button>
        </a>

    </div>
</body>
</html>

classifier_app/templates/classifier_app/result_page.html
<!DOCTYPE html>
<html lang="en">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <style>
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
</style>

<head>
    <meta charset="UTF-8">
    <title>Result</title>
</head>
<body>

    <div class="container">
        <h1 style="color:blue">Result</h1>
        <hr>
        <table>
            <tr>
                    <td><b>Sentence</b></td>
                    <td><b>Sentiment</b></td>
            </tr>
        {% for item, val in data.items %}
              <tr>
                <td>{{item}} </td>
                <td>{{val}}</td>
              </tr>
        {% endfor %}
        </table>
        <br>
        <hr>
        <a href="{% url 'classifier_app:analyze'%}">
            <button type="submit" class="btn btn-primary">
                Check More
            </button>
        </a>

    </div>

</body>
</html>

classifier_app/templates/classifier_app/search_in_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Search In File</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">

    <style>
        textarea {
          width: 50%;
          height: 150px;
          padding: 12px 20px;
          box-sizing: border-box;
          border: 2px solid #ccc;
          border-radius: 4px;
          background-color: #f8f8f8;
          font-size: 16px;
          resize: none;
        }
    </style>

</head>
<body>

    <div class="container">
        <h1 style="color:gray">Select File</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="myfile">
            <hr>
            <h2 style="color:Green">Search anything in file</h2>
            <b>Enter Text: </b>
            <br>
            <textarea cols="30" rows="5" name="query"></textarea>
            <br>
            <br>
            <a href="{% url 'classifier_app:file_search'%}">
                <button type="submit" class="btn btn-primary">
                    Search
                </button>
            </a>
      </form>
    </div>

</body>
</html>

classifier_app/templates/classifier_app/search_result_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Search Results</title>
</head>
<body>
    <div class="container">

        <h1 style="color:#5c00e6">Search results are as follows</h1>
        <hr>
        {{query | safe}}
        <hr>
        <h2>Page Numbers</h2>
        {% for num in page_locations %}
        <li>
            {{num}}
        </li>
        {% endfor %}

    </div>

<b class=""></b>

</body>
</html>

classifier_app/templates/classifier_app/show_file_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>File results</title>
</head>
<body>

  <div class="container">
      <h2> Select the operation on file</h2>
      <a href="{url 'classifier_app:SearchInFile'}">
          <button class="btn btn-success">
              Search in File
          </button>
      </a>
      <hr>
      <a href="{url 'classifier_app:'}">
          <button class="btn btn-success">
              Search in File
          </button>
      </a>

  </div>

</body>
</html>